# Implementacíon del método de K-means

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.40970236, 0.25700324, 0.33775137],
       [0.65383029, 0.6615623 , 0.4731014 ],
       [0.60922468, 0.39375739, 0.91879773],
       [0.62544037, 0.61394212, 0.27363425],
       [0.42406412, 0.17923415, 0.06592576],
       [0.05416651, 0.67041885, 0.65464463],
       [0.80942434, 0.24643775, 0.13369941],
       [0.07473219, 0.97486038, 0.01286005],
       [0.14373353, 0.07708079, 0.49161737],
       [0.91149536, 0.22467215, 0.78891041],
       [0.37996383, 0.41373089, 0.41452054],
       [0.38714642, 0.8286898 , 0.36938638],
       [0.44202451, 0.39748967, 0.80959445],
       [0.05305676, 0.51804414, 0.52518397],
       [0.89080789, 0.89560208, 0.58828006],
       [0.95563844, 0.99547578, 0.76326303],
       [0.86116027, 0.32408837, 0.98499468],
       [0.74903303, 0.64351351, 0.24290884],
       [0.27773507, 0.23193568, 0.6852417 ],
       [0.16940318, 0.53366235, 0.81591506],
       [0.89841473, 0.28927988, 0.67346143],
       [0.19071984, 0.85369076, 0.41315438],
       [0.

In [5]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.60922468, 0.39375739, 0.91879773],
       [0.86277066, 0.06854679, 0.50928278]])

In [6]:
from scipy.cluster.vq import vq

In [9]:
 c, dist = vq(data, clust_centers)

In [10]:
c

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0], dtype=int32)

In [11]:
dist

array([0.51981702, 0.52187581, 0.        , 0.63977493, 0.6334671 ,
       0.67409792, 0.41899152, 1.2017013 , 0.70671715, 0.32394573,
       0.55430584, 0.73507673, 0.19973779, 0.69260504, 0.66361068,
       0.7115185 , 0.269643  , 0.6437997 , 0.43660056, 0.47286488,
       0.27739543, 0.80147377, 0.89628336, 0.53262747, 0.75879599,
       0.51110556, 0.22473799, 0.9146536 , 0.        , 0.9965043 ])

In [12]:
from scipy.cluster.vq import kmeans

In [13]:
kmeans(data, clust_centers)

(array([[0.47648697, 0.7781329 , 0.43165385],
        [0.59653192, 0.26039213, 0.48666352]]), 0.40476803397269284)

In [14]:
kmeans(data, 2)

(array([[0.79394677, 0.53340218, 0.50245909],
        [0.24229536, 0.50310289, 0.40967251]]), 0.40410785915591446)